[metadata]
name = Wan2.1
version = 0.1.0
author = Wan-Video
description = Wan2.1 - Video generation project
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/Wan-Video/Wan2.1
license_file = LICENSE.txt

[options]
packages = find:
python_requires = >=3.8
include_package_data = True
classifiers =
    Development Status :: 3 - Alpha
    Intended Audience :: Developers
    License :: OSI Approved :: Apache License
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12

[options.packages.exclude]
tests*
examples*
docs*

[options.install_requires]
opencv-python>=4.9.0.80
diffusers>=0.31.0
accelerate>=1.1.1
imageio
easydict
ftfy
dashscope
imageio-ffmpeg
flash_attn; platform_system == "linux"

[options.extras_require]
dev =
    pytest
    wheel
    setuptools
    build

[options.entry_points]
# console_scripts =
#     wan2_process = wan_package.module:function