[metadata]
name = Wan2.1
author = Wan-Video
version = 0.1.0
url = http://github.com/Wan-Video/Wan2.1
description = Wan2.1 - Video generation project
long_description = file: README.md
long_description_content_type = text/markdown
license_files = LICENSE.txt

classifiers =
    License :: OSI Approved :: Apache Software License
    Programming Language :: Python
    Development Status :: 3 - Alpha
    Intended Audience :: Developers
    Topic :: Multimedia :: Video
    Topic :: Scientific/Engineering :: Artificial Intelligence
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12

[options]
packages = find:
install_package_data = True
python_requires = >=3.8
install_requires =
    opencv-python>=4.9.0.80
    diffusers>=0.31.0
    accelerate>=1.1.1
    imageio
    easydict
    ftfy
    dashscope
    imageio-ffmpeg
    flash_attn; platform_system == "linux"

[options.extras_require]
dev =
    pytest
    wheel
    setuptools
    build
docs =
    sphinx
    numpydoc
    myst-parser


[options.entry_points]
# console_scripts =
#     wan2_process = wan_package.module:function